# Specify the base image
FROM httpd:2.4.62

# Install any additional PHP extensions if needed
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copy your application files to the container
COPY . /var/www/html/

# Set permissions for the web server
RUN chown -R www-data:www-data /var/www/html

# Expose port 80
EXPOSE 8003

docker run --name webserver-apache-nairobi -d -v "//c/Users/aomondi/Documents/GitHub/MCS8104/MCS8104-Lab1-Containerization/container-volumes/apache/var-www-html/:/var/www/html/" -p 8002:80 -e chown -R www-data:www-data /var/www/html httpd:2.4.62

docker run --name webserver-apache-nairobi -d -v "//./container-volumes/apache/var-www-html/:/var/www/html/" -p 8002:80 httpd:2.4.62

docker run --name webserver-apache-nairobi -d -v "//./container-volumes/apache/var-www-html/:/var/www/html/" -p 8002:80 httpd:2.4.62 /bin/sh -c "chown -R www-data:www-data /var/www/html && httpd-foreground"

docker run --name webserver-apache-nairobi -d -v "//c/Users/aomondi/Documents/GitHub/MCS8104/MCS8104-Lab1-Containerization/container-volumes/apache/var-www-html/:/var/www/html/" -p 8002:80 --entrypoint /bin/bash httpd:2.4.62 -c "chown -R www-data:www-data /var/www/html && httpd-foreground"

